all:
	wget --no-clobber http://shapechange.net/resources/config/StandardMapEntries.xml
	wget --no-clobber http://shapechange.net/resources/config/StandardMapEntries_iso19136_2007.xml
	wget --no-clobber http://shapechange.net/resources/config/StandardMapEntries_iso19139_2007.xml
	wget --no-clobber http://shapechange.net/resources/config/StandardMapEntries_sweCommon.xml
	wget --no-clobber http://shapechange.net/resources/config/StandardMapEntries_gsip.xml
	wget --no-clobber http://shapechange.net/resources/config/StandardMapEntries_iso19107.xml
	wget --no-clobber http://shapechange.net/resources/config/StandardMapEntries_iso19108.xml
	wget --no-clobber http://shapechange.net/resources/config/StandardMapEntries_iso19111.xml
	wget --no-clobber http://shapechange.net/resources/config/StandardMapEntries_iso19115.xml
	wget --no-clobber http://shapechange.net/resources/config/StandardMapEntries_iso19123.xml
	wget --no-clobber http://shapechange.net/resources/config/StandardMapEntries_iso19156.xml
	wget --no-clobber http://shapechange.net/resources/config/StandardMapEntries_gmlcov.xml

clean:
	rm -f StandardMapEntries.xml
