drop table if exists elektriciteitskabel cascade;
drop table if exists oliegaschemicalien cascade;
drop table if exists kabelb cascade;
drop table v_aanduidingEisVoorzorgsmaatregel;
drop table v_Annotatie_lijn;
drop table v_Annotatie;
drop table v_BGevaarlijkeInhoud;
drop table v_Containerelement;
drop table v_Diepte;
drop table v_DT_KabelOfLeiding;
drop table v_ExtraDetailInfo;
drop table v_ExtraGeometrie;
drop table v_ExtraTopo;
drop table v_KabelEnLeidingContainer;
drop table v_Kunstwerk_Containerelement;
drop table v_Leidingelement;
drop table v_maatvoering_label;
drop table v_maatvoering_lijn;
drop table v_maatvoering_pijl;
drop table v_RioolVV_KabelOfLeiding;
drop table v_Water_KabelOfLeiding;
drop table v_elektriciteitskabel;
drop table v_oliegaschemicalien;
drop table v_kabelb;
drop table if exists relatedparty cascade;
drop table if exists utilitylink cascade;
drop table if exists mangat;
drop table if exists mast;
drop table if exists geulmof;
