all:
	wget -nc http://shapechange.net/resources/config/StandardAliases.xml
	wget -nc http://shapechange.net/resources/config/StandardStereotypeMappings-owl.xml
	wget -nc http://shapechange.net/resources/config/StandardNamespaces-owl.xml
	wget -nc http://shapechange.net/resources/config/StandardMapEntries-owl.xml
	wget -nc http://shapechange.net/resources/config/StandardMapEntries_iso19103-owl.xml
	wget -nc http://shapechange.net/resources/config/StandardMapEntries_iso19136_2007-owl.xml
	wget -nc http://shapechange.net/resources/config/StandardMapEntries_iso19107-owl.xml
	wget -nc http://shapechange.net/resources/config/StandardMapEntries_iso19115-owl.xml
	wget -nc http://shapechange.net/resources/config/StandardMapEntries_iso19156-owl.xml
